//! Format compliance against committed reference fixtures.
//!
//! `fixtures/v2-reference.5fs` is an image created by a known-good build;
//! its manifest records what it must contain. `verify_fixture` proves the
//! current code still reads it correctly (backward compatibility) and that
//! the on-disk bytes match the format spec at the raw level, independent of
//! our own parsers where possible.
//!
//! Regenerate after an intentional format change with `make fixtures`
//! (which also rewrites the manifest), and commit both files.

use gofs::fmt::*;
use gofs::fs::Gofs;
use gofs::mkfs::{mkfs, MkfsOpts};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn fixture_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures").join(name)
}

fn pattern(len: usize, seed: u8) -> Vec<u8> {
    (0..len).map(|i| (i as u64 * 31 + seed as u64) as u8).collect()
}

const FILES: &[(&str, usize, u8)] = &[
    ("hello.txt", 100, 1),            // EMBED
    ("data/medium.bin", 200_000, 2),  // inline extents
    ("data/large.bin", 3 << 20, 3),   // multi-cell
    ("日本語/ファイル.txt", 5_000, 4), // unicode names
];

#[test]
#[ignore = "regenerates the committed fixture; run via make fixtures"]
fn generate_fixture() {
    let dir = fixture_path("");
    std::fs::create_dir_all(&dir).unwrap();
    let img = fixture_path("v2-reference.5fs");
    let _ = std::fs::remove_file(&img);
    let kernel = pattern(300_000, 42);
    mkfs(
        &img,
        &MkfsOpts {
            size: Some(24 << 20),
            journal: Some(2 << 20),
            label: "reference".into(),
            kernel: Some(kernel.clone()),
            ..Default::default()
        },
    )
    .unwrap();
    let mut fs = Gofs::open(&img, true).unwrap();

    let mut manifest = String::new();
    writeln!(manifest, "# 5FS v2 reference fixture manifest — regenerated by `make fixtures`").unwrap();
    writeln!(manifest, "sb.version 2").unwrap();
    writeln!(manifest, "sb.blocksize {}", fs.sb.blocksize).unwrap();
    writeln!(manifest, "sb.inodesize {}", fs.sb.inodesize).unwrap();
    writeln!(manifest, "sb.label reference").unwrap();

    fs.mkdir("data", 0o755).unwrap();
    fs.mkdir("日本語", 0o755).unwrap();
    for (path, len, seed) in FILES {
        let data = pattern(*len, *seed);
        fs.import(path, &data, 0o644).unwrap();
        writeln!(manifest, "file {path} {len} {:08x}", crc32c::crc32c(&data)).unwrap();
    }
    // sparse TREE file: marks at 0 and 8 MiB
    {
        let ino = fs.create("sparse.bin", 0o644).unwrap();
        fs.write(ino, 0, b"start-mark").unwrap();
        fs.write(ino, 8 << 20, b"end-mark").unwrap();
        let data = fs.read_file(ino).unwrap();
        writeln!(manifest, "file sparse.bin {} {:08x}", data.len(), crc32c::crc32c(&data))
            .unwrap();
    }
    // hashed directory with 120 entries
    fs.mkdir("docs", 0o755).unwrap();
    for i in 0..120 {
        let data = pattern(64 + i, (i % 251) as u8);
        fs.import(&format!("docs/f-{i:03}"), &data, 0o644).unwrap();
    }
    writeln!(manifest, "dir docs 120").unwrap();
    // hardlink pair and symlink
    fs.import("link-target", b"shared content", 0o644).unwrap();
    let ino = fs.lookup_path("link-target").unwrap();
    let (p, _) = fs.resolve_parent("hardlink").unwrap();
    fs.link_at(ino, p, "hardlink").unwrap();
    writeln!(manifest, "hardlink hardlink link-target").unwrap();
    let (p, n) = fs.resolve_parent("sym").unwrap();
    fs.symlink_at(p, &n, "hello.txt").unwrap();
    writeln!(manifest, "symlink sym hello.txt").unwrap();
    writeln!(manifest, "kernel {} {:08x}", kernel.len(), crc32c::crc32c(&kernel)).unwrap();
    drop(fs);

    let r = gofs::fsck::check(&img).unwrap();
    assert!(r.clean(), "fixture must be clean: {:#?}", r.errors);
    std::fs::write(fixture_path("v2-reference.manifest"), manifest).unwrap();
    eprintln!("fixture regenerated: {}", img.display());
}

#[test]
fn verify_fixture() {
    let img = fixture_path("v2-reference.5fs");
    assert!(img.exists(), "missing fixture — run `make fixtures` and commit it");
    let manifest = std::fs::read_to_string(fixture_path("v2-reference.manifest")).unwrap();

    // the image must fsck clean
    let r = gofs::fsck::check(&img).unwrap();
    assert!(r.errors.is_empty(), "fsck errors: {:#?}", r.errors);
    assert!(r.warnings.is_empty(), "fsck warnings: {:#?}", r.warnings);

    let fs = Gofs::open(&img, false).unwrap();
    for line in manifest.lines().filter(|l| !l.is_empty() && !l.starts_with('#')) {
        let f: Vec<&str> = line.split(' ').collect();
        match f[0] {
            "sb.version" => assert_eq!(f[1], "2"),
            "sb.blocksize" => assert_eq!(fs.sb.blocksize.to_string(), f[1]),
            "sb.inodesize" => assert_eq!(fs.sb.inodesize.to_string(), f[1]),
            "sb.label" => assert_eq!(fs.sb.label(), f[1]),
            "file" => {
                let ino = fs.lookup_path(f[1]).unwrap_or_else(|e| panic!("{}: {e}", f[1]));
                let data = fs.read_file(ino).unwrap();
                assert_eq!(data.len().to_string(), f[2], "{}: size", f[1]);
                assert_eq!(format!("{:08x}", crc32c::crc32c(&data)), f[3], "{}: crc", f[1]);
            }
            "dir" => {
                let ino = fs.lookup_path(f[1]).unwrap();
                assert_eq!(fs.dir_entries(ino).unwrap().len().to_string(), f[2], "{}", f[1]);
            }
            "hardlink" => {
                let a = fs.lookup_path(f[1]).unwrap();
                let b = fs.lookup_path(f[2]).unwrap();
                assert_eq!(a, b, "hardlink inodes differ");
                assert_eq!(fs.read_inode(a).unwrap().nlink, 2);
            }
            "symlink" => {
                let ino = fs.lookup_path(f[1]).unwrap();
                assert_eq!(fs.readlink(ino).unwrap(), f[2]);
            }
            "kernel" => {
                let len: usize = f[1].parse().unwrap();
                // the bootloader contract: raw bytes at the physical offset
                let mut raw = vec![0u8; len];
                fs.dev.pread(&mut raw, fs.sb.kernel_offset).unwrap();
                assert_eq!(format!("{:08x}", crc32c::crc32c(&raw)), f[2], "kernel raw crc");
                assert_eq!(fs.sb.kernel_end - fs.sb.kernel_offset, len as u64);
                let ino = fs.lookup_path("kernel.bin").unwrap();
                assert_ne!(fs.read_inode(ino).unwrap().flags & INODE_FLAG_IMMUTABLE, 0);
            }
            other => panic!("unknown manifest entry {other}"),
        }
    }
}

/// Raw byte-level format checks: structures sit where the spec says, with
/// valid magics and checksums, verified without going through the parsers.
#[test]
fn raw_format_compliance() {
    let img = fixture_path("v2-reference.5fs");
    assert!(img.exists(), "missing fixture — run `make fixtures` and commit it");
    let raw = std::fs::read(&img).unwrap();
    let be32 = |off: usize| u32::from_be_bytes(raw[off..off + 4].try_into().unwrap());
    let be16 = |off: usize| u16::from_be_bytes(raw[off..off + 2].try_into().unwrap());

    // superblock at offset 0
    assert_eq!(&raw[0..4], b"5FSB", "superblock magic");
    let sb_csum = {
        let mut b = raw[..SB_SIZE].to_vec();
        b[4..8].fill(0);
        crc32c::crc32c(&b)
    };
    assert_eq!(be32(4), sb_csum, "superblock checksum (independent recomputation)");
    assert_eq!(be32(8), 2, "version is big-endian 2");
    let bs = be32(36) as usize;
    assert!(bs.is_power_of_two() && bs >= 2048, "blocksize");
    assert_eq!(be16(40), 256, "inodesize");

    // AG 0 header at block 1
    assert_eq!(&raw[bs..bs + 4], b"5FSH", "AG header magic");
    assert_eq!(be32(bs + 8), 0, "AG header ag_num");

    // both AG map copies at the recorded physical offset
    let agmap_off = u64::from_be_bytes(raw[102..110].try_into().unwrap()) as usize;
    let agmap_len = u64::from_be_bytes(raw[110..118].try_into().unwrap()) as usize;
    assert_eq!(&raw[agmap_off..agmap_off + 4], b"5FSM", "AG map copy 0 magic");
    assert_eq!(&raw[agmap_off + agmap_len..agmap_off + agmap_len + 4], b"5FSM", "copy 1 magic");

    // backup superblock in the last block of AG 0
    let ag0_len = be32(bs + 20) as usize;
    let bak = (ag0_len - 1) * bs;
    assert_eq!(&raw[bak..bak + 4], b"5FSB", "backup superblock magic");
    assert_eq!(&raw[bak..bak + SB_SIZE], &raw[..SB_SIZE], "backup equals primary");

    // root inode: "IN" magic at the slot the superblock points to
    let root_ino = u64::from_be_bytes(raw[90..98].try_into().unwrap());
    let slot = (root_ino & 0xffff_ffff) as usize;
    let ino_off = slot * 256;
    assert_eq!(be16(ino_off), 0x494e, "root inode magic");
    assert_eq!(raw[ino_off + 2], 2, "root inode version");

    // kernel physically contiguous at the superblock offset
    let koff = u64::from_be_bytes(raw[134..142].try_into().unwrap()) as usize;
    let kend = u64::from_be_bytes(raw[142..150].try_into().unwrap()) as usize;
    assert!(koff > 0 && kend > koff && kend <= ag0_len * bs, "kernel region inside AG 0");
    assert_eq!(crc32c::crc32c(&pattern(kend - koff, 42)), crc32c::crc32c(&raw[koff..kend]));
}
